on:
    push:
      branches:
        - "main"
name: Building Production
jobs:
  install-build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout "main" branch 😰
      uses: actions/checkout@v2
    - name: Set up Node.js 👻
      uses: actions/setup-node@v2
      with:
        node-version: '18.14.2'
    - name: Install Dependencies 🗂
      run: npm install --save
    - name: Build Project 🚌
      env:
        CI: false
      run: npm run build
    - name: Sync File 🥵
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server:  ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ${{ secrets.FTP_PROTOCOL }}
        port: ${{ secrets.FTP_PORT }}
        local-dir: ./build/